export const PUBLIC_GENERATION_ERROR_CODES = [
  "QUOTA_EXHAUSTED",
  "IP_QUOTA_EXHAUSTED",
  "RATE_LIMITED",
  "INVALID_REQUEST",
  "INVALID_IMAGE",
  "REQUEST_TOO_LARGE",
  "PROVIDER_REJECTED",
  "PROVIDER_TIMEOUT",
  "SERVICE_UNAVAILABLE",
  "PUBLIC_GENERATION_OFF",
] as const;

export type PublicGenerationErrorCode = (typeof PUBLIC_GENERATION_ERROR_CODES)[number];
